// ==UserScript==
// @name Phish-me, Spam You
// @namespace Evil Tools agqainst Evil
// @match https://excel.officeapps.live.com/x/_layouts/xlform.aspx?ui=en-US&rs=en-US&hid=*WOPISrc=https%3A%2F%2Fwopi.onedrive.com%2Fwopi%2Ffiles%2F1299051320C3873E%21113&sc=host%3D%26qt%3DFolders&mscc=1&wdFormId=%7b573C3764-E34A-45DB-8EE6-8D8C672404A8%7d
// @match https://reader.miniflux.app/unread
// @grant none
// @run-at       document-idle
// ==/UserScript==

(function () {
	function Sleep(condition, func) {
		if (condition()) {
			func()
		}
		else {
			setTimeout(_ => Sleep(condition, func))
		}
	}

	// Sleep(
	// 	_ => !($("#Question0 #QuestionAnswerElement")[0] === undefined),
	// 	_ => {
	// 		$("#Question0 #QuestionAnswerElement").val("Other")[0].dispatchEvent(new Event('change'))
	// 		$("#Question1 #QuestionAnswerElement").val(Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15))[0].dispatchEvent(new Event('change'))
	// 		$("#Question2 #QuestionAnswerElement").val(Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15))[0].dispatchEvent(new Event('change'))
	// 		$("#m_submitButton").click()
	// 		Sleep(
	// 			_ => !($("#ewrform-messagearea")[0] === undefined),
	// 			_ => { location.reload() }
	// 		)
	// 	}
	// )

    
    function User() {
        this.FirstName = firstNames[(Math.random() * firstNames.length) | 0];
        this.LastName = lastNames[(Math.random() * lastNames.length) | 0];
        this.Email = `${this.FirstName}.${this.LastName}@${domains[(Math.random() * domains.length) | 0]}`;
        this.Password = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
    }

    // TODO: Move to json file
    let domains = [
        "example.com"
    ]
    
    // TODO: Move to json file
    let firstNames = [
		"Aaron",
		"Abigail",
		"Adam",
		"Alan",
		"Albert",
		"Alexander",
		"Alexis",
		"Alice",
		"Amanda",
		"Amber",
		"Amy",
		"Andrea",
		"Andrew",
		"Angela",
		"Ann",
		"Anna",
		"Anthony",
		"Arthur",
		"Ashley",
		"Austin",
		"Barbara",
		"Benjamin",
		"Betty",
		"Beverly",
		"Billy",
		"Bobby",
		"Bradley",
		"Brandon",
		"Brenda",
		"Brian",
		"Brittany",
		"Bruce",
		"Bryan",
		"Carl",
		"Carol",
		"Carolyn",
		"Catherine",
		"Charles",
		"Cheryl",
		"Christian",
		"Christina",
		"Christine",
		"Christopher",
		"Cynthia",
		"Daniel",
		"Danielle",
		"David",
		"Deborah",
		"Debra",
		"Denise",
		"Dennis",
		"Diana",
		"Diane",
		"Donald",
		"Donna",
		"Doris",
		"Dorothy",
		"Douglas",
		"Dylan",
		"Edward",
		"Elizabeth",
		"Emily",
		"Emma",
		"Eric",
		"Ethan",
		"Eugene",
		"Evelyn",
		"Frances",
		"Frank",
		"Gabriel",
		"Gary",
		"George",
		"Gerald",
		"Gloria",
		"Grace",
		"Gregory",
		"Hannah",
		"Harold",
		"Heather",
		"Helen",
		"Henry",
		"Jack",
		"Jacob",
		"Jacqueline",
		"James",
		"Jane",
		"Janet",
		"Janice",
		"Jason",
		"Jean",
		"Jeffrey",
		"Jennifer",
		"Jeremy",
		"Jerry",
		"Jesse",
		"Jessica",
		"Joan",
		"Joe",
		"John",
		"Johnny",
		"Jonathan",
		"Jordan",
		"Jose",
		"Joseph",
		"Joshua",
		"Joyce",
		"Juan",
		"Judith",
		"Judy",
		"Julia",
		"Julie",
		"Justin",
		"Karen",
		"Katherine",
		"Kathleen",
		"Kathryn",
		"Kayla",
		"Keith",
		"Kelly",
		"Kenneth",
		"Kevin",
		"Kimberly",
		"Kyle",
		"Larry",
		"Laura",
		"Lauren",
		"Lawrence",
		"Linda",
		"Lisa",
		"Logan",
		"Lori",
		"Louis",
		"Madison",
		"Margaret",
		"Maria",
		"Marie",
		"Marilyn",
		"Mark",
		"Martha",
		"Mary",
		"Matthew",
		"Megan",
		"Melissa",
		"Michael",
		"Michelle",
		"Nancy",
		"Natalie",
		"Nathan",
		"Nicholas",
		"Nicole",
		"Noah",
		"Olivia",
		"Pamela",
		"Patricia",
		"Patrick",
		"Paul",
		"Peter",
		"Philip",
		"Rachel",
		"Ralph",
		"Randy",
		"Raymond",
		"Rebecca",
		"Richard",
		"Robert",
		"Roger",
		"Ronald",
		"Rose",
		"Roy",
		"Russell",
		"Ruth",
		"Ryan",
		"Samantha",
		"Samuel",
		"Sandra",
		"Sara",
		"Sarah",
		"Scott",
		"Sean",
		"Sharon",
		"Shirley",
		"Sophia",
		"Stephanie",
		"Stephen",
		"Steven",
		"Susan",
		"Teresa",
		"Terry",
		"Theresa",
		"Thomas",
		"Timothy",
		"Tyler",
		"Victoria",
		"Vincent",
		"Virginia",
		"Walter",
		"Wayne",
		"William",
		"Willie",
		"Zachary"
    ]
    // TODO: Move to json file
    let lastNames = [
        "Smith",
        "Johnson",
        "Williams",
        "Jones",
        "Brown",
        "Davis",
        "Miller",
        "Wilson",
        "Moore",
        "Taylor",
        "Anderson",
        "Thomas",
        "Jackson",
        "White",
        "Harris",
        "Martin",
        "Thompson",
        "Garcia",
        "Martinez",
        "Robinson",
        "Clark",
        "Rodriguez",
        "Lewis",
        "Lee",
        "Walker",
        "Hall",
        "Allen",
        "Young",
        "Hernandez",
        "King",
        "Wright",
        "Lopez",
        "Hill",
        "Scott",
        "Green",
        "Adams",
        "Baker",
        "Gonzalez",
        "Nelson",
        "Carter",
        "Mitchell",
        "Perez",
        "Roberts",
        "Turner",
        "Phillips",
        "Campbell",
        "Parker",
        "Evans",
        "Edwards",
        "Collins",
        "Stewart",
        "Sanchez",
        "Morris",
        "Rogers",
        "Reed",
        "Cook",
        "Morgan",
        "Bell",
        "Murphy",
        "Bailey",
        "Rivera",
        "Cooper",
        "Richardson",
        "Cox",
        "Howard",
        "Ward",
        "Torres",
        "Peterson",
        "Gray",
        "Ramirez",
        "James",
        "Watson",
        "Brooks",
        "Kelly",
        "Sanders",
        "Price",
        "Bennett",
        "Wood",
        "Barnes",
        "Ross",
        "Henderson",
        "Coleman",
        "Jenkins",
        "Perry",
        "Powell",
        "Long",
        "Patterson",
        "Hughes",
        "Flores",
        "Washington",
        "Butler",
        "Simmons",
        "Foster",
        "Gonzales",
        "Bryant",
        "Alexander",
        "Russell",
        "Griffin",
        "Diaz",
        "Hayes"
    ]
})()
